//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allowance
    {
        public int AllowanceID { get; set; }
        public string AllowanceName { get; set; }
        public string AllowanceType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool IsPercentage { get; set; }
        public string PercentageOf { get; set; }
        public bool IsTaxable { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    }
}
