//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSettingsDetail
    {
        public int ID { get; set; }
        public string AppSettingsDetailKey { get; set; }
        public string AppSettingDetailValue { get; set; }
        public Nullable<int> AppSettingsID { get; set; }
        public Nullable<bool> IsPerHour { get; set; }
        public Nullable<bool> IsMinimumFor24Hours { get; set; }
        public Nullable<bool> IsPercentage { get; set; }
        public Nullable<int> DivisionMasterTypeID { get; set; }
        public Nullable<int> RelatedPartyOrderID { get; set; }
    }
}
