//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDetail
    {
        public int ID { get; set; }
        public Nullable<int> RelatedPartyID { get; set; }
        public Nullable<int> WorkedMonth { get; set; }
        public Nullable<int> WorkedYear { get; set; }
        public Nullable<bool> IsOTRecommended { get; set; }
    }
}
