//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceRecord
    {
        public int ID { get; set; }
        public Nullable<int> EPFNo { get; set; }
        public Nullable<System.DateTime> AttendanceDateTime { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
