//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceRecord
    {
        public int AttendanceID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public int ShiftID { get; set; }
        public Nullable<System.DateTime> ScheduledIn { get; set; }
        public Nullable<System.DateTime> ScheduledOut { get; set; }
        public Nullable<System.DateTime> ActualIn { get; set; }
        public Nullable<System.DateTime> ActualOut { get; set; }
        public Nullable<decimal> TotalHours { get; set; }
        public Nullable<decimal> OvertimeHours { get; set; }
        public Nullable<decimal> NightHours { get; set; }
        public Nullable<int> LateMinutes { get; set; }
        public Nullable<int> EarlyOutMinutes { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public bool IsRegularized { get; set; }
        public Nullable<int> RegularizedBy { get; set; }
        public Nullable<System.DateTime> RegularizedDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
