//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDeposit
    {
        public int ID { get; set; }
        public Nullable<decimal> Pharmacy_Deposit { get; set; }
        public Nullable<decimal> Reception_Deposit { get; set; }
        public Nullable<System.DateTime> DepositDatetime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<decimal> Cheque_Deposit { get; set; }
        public Nullable<decimal> CashInHand { get; set; }
    }
}
