//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchPopup
    {
        public int ID { get; set; }
        public Nullable<int> DivisionChargeID { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<System.DateTime> OpeningStockDate { get; set; }
        public Nullable<decimal> OpeningStock { get; set; }
        public Nullable<decimal> BatchSellingPrice { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
    }
}
