//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillFinalization_Last
    {
        public int ID { get; set; }
        public Nullable<int> AppSettingDetailID { get; set; }
        public Nullable<int> RelatedPartySessionID { get; set; }
        public string ChargeName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsPerHour { get; set; }
        public Nullable<bool> IsMinimumFor24Hours { get; set; }
        public Nullable<decimal> PerDayValue { get; set; }
        public Nullable<decimal> NoOfHours { get; set; }
        public Nullable<bool> IsPercentage { get; set; }
        public Nullable<int> DivisionMasterTypeID { get; set; }
        public Nullable<int> RelatedPartyOrderID { get; set; }
        public Nullable<bool> IsThisBillIncentive { get; set; }
        public Nullable<System.DateTime> SnapShotDateTime { get; set; }
        public Nullable<int> ConsultantID { get; set; }
    }
}
