//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelingSquence
    {
        public int ID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<System.DateTime> ChannelDate { get; set; }
        public Nullable<int> TimeSlotID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> SquenceStatus { get; set; }
        public string Times { get; set; }
        public Nullable<int> PatientLimits { get; set; }
        public Nullable<int> DivisionMasterID { get; set; }
        public Nullable<int> TimeInterval { get; set; }
    }
}
