//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeDiscount
    {
        public int ID { get; set; }
        public string DiscountTypeName { get; set; }
        public Nullable<int> DiscountTypeCode { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<int> ChargeTypeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> RelatedPartyTypeID { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
    }
}
