//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeMasterPrice
    {
        public int ID { get; set; }
        public Nullable<int> ChargeMasterID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<int> RefDivisionMasterID { get; set; }
    
        public virtual ChargeMaster ChargeMaster { get; set; }
        public virtual OrderType OrderType { get; set; }
    }
}
