//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChargeMaster()
        {
            this.ChargeMasterPrices = new HashSet<ChargeMasterPrice>();
            this.DivisionCharges = new HashSet<DivisionCharge>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Code { get; set; }
        public Nullable<int> UnitTypeID { get; set; }
        public Nullable<int> MenuTypeID { get; set; }
        public Nullable<int> MenuTypeDetailID { get; set; }
        public Nullable<int> ChargeTypeID { get; set; }
        public Nullable<int> ChargeCategoryID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<bool> IsIncentiveCalculate { get; set; }
    
        public virtual ChargeType ChargeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeMasterPrice> ChargeMasterPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DivisionCharge> DivisionCharges { get; set; }
    }
}
