//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckManagment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string InvoiceNo { get; set; }
        public string CheckNumber { get; set; }
        public Nullable<int> RelatedpartyID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> DivisionMasterID { get; set; }
        public Nullable<int> PaymentCategoryID { get; set; }
        public Nullable<int> ChequeType { get; set; }
        public Nullable<int> IsIssued { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<System.DateTime> IssueDateTime { get; set; }
    }
}
