//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentPayrollMonth
    {
        public int ID { get; set; }
        public Nullable<int> CurrentPayrollMonthValue { get; set; }
        public Nullable<int> CurrentPayrollYearValue { get; set; }
        public Nullable<int> SalaryTypeID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> IsCurrentPayrollMonth { get; set; }
        public string MonthName { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<System.DateTime> DurationFrom { get; set; }
        public Nullable<System.DateTime> DurationTo { get; set; }
    }
}
