//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public int ID { get; set; }
        public string designationName { get; set; }
        public Nullable<System.DateTime> AttendanceInCaptureStart { get; set; }
        public Nullable<System.DateTime> AttendanceInCaptureEnd { get; set; }
        public Nullable<System.DateTime> AttendanceOutCaptureStart { get; set; }
        public Nullable<System.DateTime> AttendanceOutCaptureEnd { get; set; }
        public Nullable<System.DateTime> ExpectedIn { get; set; }
        public Nullable<System.DateTime> ExpectedOut { get; set; }
    }
}
