//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionMasterType
    {
        public int ID { get; set; }
        public string DivisionMasterTypeName { get; set; }
        public Nullable<int> DivisionMasterID { get; set; }
        public string DivisionMasterTypeDescription { get; set; }
        public Nullable<int> ParentDivisionMasterTypeID { get; set; }
    }
}
