//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionCharge
    {
        public int ID { get; set; }
        public Nullable<int> ChargeMasterID { get; set; }
        public Nullable<int> DivisionMasterID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> OpeningBalanceDate { get; set; }
        public Nullable<int> ChargeTypeID { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> ReorderLevel { get; set; }
        public Nullable<int> ChargeMasterPriceID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<bool> IsBoxItem { get; set; }
        public Nullable<decimal> PerBoxQty { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<decimal> WardPharmacyPrice { get; set; }
        public Nullable<int> ParentDivisionChargeID { get; set; }
        public Nullable<int> ConsultantID { get; set; }
        public Nullable<decimal> PhysicalStock { get; set; }
        public Nullable<decimal> OpeningStock { get; set; }
        public Nullable<bool> IsIncentiveCalculate { get; set; }
        public Nullable<int> AttachmentID { get; set; }
    
        public virtual ChargeMaster ChargeMaster { get; set; }
        public virtual ChargeType ChargeType { get; set; }
        public virtual DivisionMaster DivisionMaster { get; set; }
    }
}
