//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DivisionMaster()
        {
            this.DivisionCharges = new HashSet<DivisionCharge>();
        }
    
        public int ID { get; set; }
        public string DivisionMasterName { get; set; }
        public string DivisionMasterCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> MenuTypeID { get; set; }
        public Nullable<int> MenuTypeDetailID { get; set; }
        public string DivisionMasterDescription { get; set; }
        public Nullable<bool> IsStockManaged { get; set; }
        public Nullable<int> ParentDivisionMasterID { get; set; }
        public Nullable<int> DivisionMasterTypeID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public Nullable<decimal> OrderSequence { get; set; }
        public Nullable<bool> IsReserved { get; set; }
        public Nullable<int> AccoutClassID { get; set; }
        public Nullable<int> AccoutClassCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DivisionCharge> DivisionCharges { get; set; }
    }
}
