//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorDivisionChargeMapping
    {
        public int ID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> DivisionChargeID { get; set; }
        public Nullable<int> DivisionMasterID { get; set; }
        public Nullable<decimal> DoctorCharge { get; set; }
        public Nullable<decimal> HospitalCharge { get; set; }
        public Nullable<decimal> WardDoctorCharge { get; set; }
        public Nullable<decimal> TechnicianCharge { get; set; }
    }
}
