//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBankAccount
    {
        public int AccountID { get; set; }
        public int EmployeeID { get; set; }
        public int BankID { get; set; }
        public int BranchID { get; set; }
        public string AccountNumber { get; set; }
        public string AccountHolderName { get; set; }
        public bool IsPrimary { get; set; }
        public bool IsActive { get; set; }
    }
}
