//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTraining
    {
        public int TrainingID { get; set; }
        public int EmployeeID { get; set; }
        public string TrainingName { get; set; }
        public string TrainingProvider { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Duration { get; set; }
        public string Status { get; set; }
        public string CertificatePath { get; set; }
        public string Remarks { get; set; }
    }
}
