//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeNumber { get; set; }
        public string EPFNumber { get; set; }
        public string ETFNumber { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string NIC { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactPhone { get; set; }
        public string EmergencyContactRelation { get; set; }
        public string Address { get; set; }
        public System.DateTime DateOfJoin { get; set; }
        public Nullable<System.DateTime> DateOfResignation { get; set; }
        public bool IsActive { get; set; }
        public decimal BasicSalary { get; set; }
        public int DesignationID { get; set; }
        public int EmployeeTypeID { get; set; }
        public int CategoryID { get; set; }
        public int CompanyID { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> WardID { get; set; }
        public Nullable<int> SpecializationID { get; set; }
        public string MedicalLicenseNo { get; set; }
        public Nullable<System.DateTime> LicenseExpiryDate { get; set; }
        public string BloodGroup { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
