//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeQualification
    {
        public int QualificationID { get; set; }
        public int EmployeeID { get; set; }
        public string Qualification { get; set; }
        public string Institution { get; set; }
        public Nullable<int> Year { get; set; }
        public string Grade { get; set; }
        public string DocumentPath { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
    }
}
