//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HREntities : DbContext
    {
        public HREntities()
            : base("name=HREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AdmissionCategory> AdmissionCategories { get; set; }
        public virtual DbSet<AdmissionType> AdmissionTypes { get; set; }
        public virtual DbSet<Allowance> Allowances { get; set; }
        public virtual DbSet<AppSetting> AppSettings { get; set; }
        public virtual DbSet<AppSettingsDetail> AppSettingsDetails { get; set; }
        public virtual DbSet<AttendanceData> AttendanceDatas { get; set; }
        public virtual DbSet<AttendanceDetail> AttendanceDetails { get; set; }
        public virtual DbSet<AttendanceLastRecordDetail> AttendanceLastRecordDetails { get; set; }
        public virtual DbSet<AttendanceRecord> AttendanceRecords { get; set; }
        public virtual DbSet<AttendanceTime> AttendanceTimes { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BankBranch> BankBranches { get; set; }
        public virtual DbSet<BankDeposit> BankDeposits { get; set; }
        public virtual DbSet<BatchPopup> BatchPopups { get; set; }
        public virtual DbSet<BillFinalization> BillFinalizations { get; set; }
        public virtual DbSet<BillFinalization_Last> BillFinalization_Last { get; set; }
        public virtual DbSet<CalanderForPayout> CalanderForPayouts { get; set; }
        public virtual DbSet<ChannelingSquence> ChannelingSquences { get; set; }
        public virtual DbSet<ChannelingTimeSlot> ChannelingTimeSlots { get; set; }
        public virtual DbSet<ChargeCategory> ChargeCategories { get; set; }
        public virtual DbSet<ChargeDiscount> ChargeDiscounts { get; set; }
        public virtual DbSet<ChargeItemList> ChargeItemLists { get; set; }
        public virtual DbSet<ChargeMaster> ChargeMasters { get; set; }
        public virtual DbSet<ChargeMasterPrice> ChargeMasterPrices { get; set; }
        public virtual DbSet<ChargeType> ChargeTypes { get; set; }
        public virtual DbSet<CheckManagment> CheckManagments { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CreditCardType> CreditCardTypes { get; set; }
        public virtual DbSet<CurrentPayrollMonth> CurrentPayrollMonths { get; set; }
        public virtual DbSet<DayType> DayTypes { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<DivisionCharge> DivisionCharges { get; set; }
        public virtual DbSet<DivisionMaster> DivisionMasters { get; set; }
        public virtual DbSet<DivisionMasterOrderTypeMapping> DivisionMasterOrderTypeMappings { get; set; }
        public virtual DbSet<DivisionMasterType> DivisionMasterTypes { get; set; }
        public virtual DbSet<DoctorDivisionChargeMapping> DoctorDivisionChargeMappings { get; set; }
        public virtual DbSet<DoctorWiseTimeSlot> DoctorWiseTimeSlots { get; set; }
        public virtual DbSet<InPatientInsuranceClaim> InPatientInsuranceClaims { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<LeaveCategory> LeaveCategories { get; set; }
        public virtual DbSet<LeaveMaster> LeaveMasters { get; set; }
        public virtual DbSet<LeaveStatu> LeaveStatus { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<LoanCategory> LoanCategories { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LogDetail> LogDetails { get; set; }
        public virtual DbSet<MenuConfiguration> MenuConfigurations { get; set; }
        public virtual DbSet<Nopay> Nopays { get; set; }
        public virtual DbSet<NurseShift> NurseShifts { get; set; }
        public virtual DbSet<OPDSquence> OPDSquences { get; set; }
        public virtual DbSet<OPDTimeSlot> OPDTimeSlots { get; set; }
        public virtual DbSet<OrderType> OrderTypes { get; set; }
        public virtual DbSet<OTType> OTTypes { get; set; }
        public virtual DbSet<PayeeTax> PayeeTaxes { get; set; }
        public virtual DbSet<PaymentCategory> PaymentCategories { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<PaymentSubCategory> PaymentSubCategories { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<PayMonthMaster> PayMonthMasters { get; set; }
        public virtual DbSet<PayrollRecord> PayrollRecords { get; set; }
        public virtual DbSet<RelatedParty> RelatedParties { get; set; }
        public virtual DbSet<RelatedPartyBankAccount> RelatedPartyBankAccounts { get; set; }
        public virtual DbSet<RelatedPartyCategory> RelatedPartyCategories { get; set; }
        public virtual DbSet<RelatedPartyDefaultSalaryModifier> RelatedPartyDefaultSalaryModifiers { get; set; }
        public virtual DbSet<RelatedPartyFixedRoster> RelatedPartyFixedRosters { get; set; }
        public virtual DbSet<RelatedPartyLeaveAllocation> RelatedPartyLeaveAllocations { get; set; }
        public virtual DbSet<RelatedPartyLeaveType> RelatedPartyLeaveTypes { get; set; }
        public virtual DbSet<RelatedPartyLoan> RelatedPartyLoans { get; set; }
        public virtual DbSet<RelatedPartyLoan1> RelatedPartyLoans1 { get; set; }
        public virtual DbSet<RelatedPartyOrder> RelatedPartyOrders { get; set; }
        public virtual DbSet<RelatedPartyOrderDetail> RelatedPartyOrderDetails { get; set; }
        public virtual DbSet<RelatedPartyOrderPayment> RelatedPartyOrderPayments { get; set; }
        public virtual DbSet<RelatedPartyRole> RelatedPartyRoles { get; set; }
        public virtual DbSet<RelatedPartyRoleAndSplashScreenItemMapping> RelatedPartyRoleAndSplashScreenItemMappings { get; set; }
        public virtual DbSet<RelatedPartySalary> RelatedPartySalaries { get; set; }
        public virtual DbSet<RelatedPartySalaryBankAccountsMapping> RelatedPartySalaryBankAccountsMappings { get; set; }
        public virtual DbSet<RelatedPartySalaryModifierMapping> RelatedPartySalaryModifierMappings { get; set; }
        public virtual DbSet<RelatedPartySession> RelatedPartySessions { get; set; }
        public virtual DbSet<RelatedPartySessionType> RelatedPartySessionTypes { get; set; }
        public virtual DbSet<RelatedPartySubCategory> RelatedPartySubCategories { get; set; }
        public virtual DbSet<RelatedPartyType> RelatedPartyTypes { get; set; }
        public virtual DbSet<RosterStatu> RosterStatus { get; set; }
        public virtual DbSet<RosterType> RosterTypes { get; set; }
        public virtual DbSet<SalaryModifierDefaultValue> SalaryModifierDefaultValues { get; set; }
        public virtual DbSet<SalaryModifier> SalaryModifiers { get; set; }
        public virtual DbSet<SalaryModifierType> SalaryModifierTypes { get; set; }
        public virtual DbSet<SalaryType> SalaryTypes { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<SplashScreenItem> SplashScreenItems { get; set; }
        public virtual DbSet<SystemLog> SystemLogs { get; set; }
        public virtual DbSet<TaxType> TaxTypes { get; set; }
        public virtual DbSet<UnitType> UnitTypes { get; set; }
    }
}
