//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InPatientInsuranceClaim
    {
        public int ID { get; set; }
        public Nullable<int> RelatedPartySessionID { get; set; }
        public string CustomerName { get; set; }
        public string PatientName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<decimal> ClaimAmount { get; set; }
        public Nullable<decimal> ReceivedAmount { get; set; }
        public string BillNo { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsChequeReceived { get; set; }
    }
}
