//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanInstallment
    {
        public int InstallmentID { get; set; }
        public int LoanID { get; set; }
        public int InstallmentNumber { get; set; }
        public System.DateTime DueDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public string Remarks { get; set; }
    }
}
