//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanCategory
    {
        public int LoanCategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public decimal InterestRate { get; set; }
        public Nullable<int> MaxInstallments { get; set; }
        public bool IsActive { get; set; }
    }
}
