//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDetail
    {
        public int id { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
        public Nullable<int> usr_sys_code { get; set; }
        public Nullable<int> RelatedID { get; set; }
        public string RelatedTable { get; set; }
        public string log_desc { get; set; }
        public string log_event { get; set; }
    }
}
