//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuConfiguration
    {
        public int ID { get; set; }
        public string MenuItemName { get; set; }
        public string MenuItemDescription { get; set; }
        public Nullable<int> ParentMenuItemID { get; set; }
        public Nullable<int> MenuLevel { get; set; }
        public string MenuItemControlName { get; set; }
        public string UIType { get; set; }
        public Nullable<int> MenuTypeID { get; set; }
        public Nullable<int> MenuTypeDetailID { get; set; }
        public Nullable<int> SplashScreenItemID { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<int> DivisionMasterID { get; set; }
        public Nullable<int> ChargeTypeID { get; set; }
        public Nullable<int> RelatedPartyTypeID { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public Nullable<bool> IsSellWardPharmacyPrice { get; set; }
        public Nullable<int> AdmissionTypeID { get; set; }
    }
}
