//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NurseShift
    {
        public int ID { get; set; }
        public Nullable<int> AdmissionType { get; set; }
        public Nullable<int> ReceivedNurse { get; set; }
        public Nullable<int> NurseInChargeAdditional { get; set; }
        public Nullable<int> AssitantNurse { get; set; }
        public Nullable<int> NurseInCharge { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> RelatedPartySessionID { get; set; }
    }
}
