//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int ID { get; set; }
        public Nullable<int> ChargeItemListID { get; set; }
        public Nullable<int> AdmissionType { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Drawer { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public string PatientName { get; set; }
        public string BHT { get; set; }
        public Nullable<decimal> DoctorCharge { get; set; }
        public Nullable<decimal> HospitalCharge { get; set; }
        public string Reason { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<byte> OrderStatus { get; set; }
        public string ReceivedBy { get; set; }
        public string Description { get; set; }
        public Nullable<int> IsPosted { get; set; }
        public Nullable<int> IsCancelPosted { get; set; }
    }
}
