//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceAppraisal
    {
        public int AppraisalID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime AppraisalDate { get; set; }
        public string AppraisalPeriod { get; set; }
        public Nullable<decimal> OverallRating { get; set; }
        public string RatingScale { get; set; }
        public string Strengths { get; set; }
        public string AreasForImprovement { get; set; }
        public string Goals { get; set; }
        public int AppraisedBy { get; set; }
        public Nullable<System.DateTime> NextAppraisalDate { get; set; }
        public string Remarks { get; set; }
    }
}
