//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedParty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RelatedParty()
        {
            this.Allowances = new HashSet<Allowance>();
            this.PayrollRecords = new HashSet<PayrollRecord>();
            this.RelatedPartyDefaultSalaryModifiers = new HashSet<RelatedPartyDefaultSalaryModifier>();
            this.RelatedPartySalaries = new HashSet<RelatedPartySalary>();
        }
    
        public int ID { get; set; }
        public string RegistrationNumber { get; set; }
        public string RelatedPartyName { get; set; }
        public string RelatedPartyAddress { get; set; }
        public string RelatedPartyNIC { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<int> DivisionMasterID { get; set; }
        public Nullable<int> RelatedPartyTypeID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<int> RelatedPartyCategoryID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public string TelephoneNumberList { get; set; }
        public string MobileNoList { get; set; }
        public Nullable<System.DateTime> DateofJoin { get; set; }
        public Nullable<System.DateTime> DateofResignation { get; set; }
        public string UserName { get; set; }
        public string RelatedPartyPassword { get; set; }
        public Nullable<int> RelatedPartyRoleID { get; set; }
        public Nullable<int> DefaultSplashScreenItemID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Weight { get; set; }
        public string Height { get; set; }
        public Nullable<bool> IsDivisionHead { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public string RelatedPartyEmail { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CompanyName { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<System.DateTime> DiscountAppliedDate { get; set; }
        public Nullable<bool> IsDiscountApplicable { get; set; }
        public Nullable<decimal> DailyPaidAmount { get; set; }
        public Nullable<decimal> ChannellingConsultantCharge { get; set; }
        public Nullable<decimal> ChannellingHospitalCharge { get; set; }
        public string Age { get; set; }
        public Nullable<int> RelatedPartySubCategoryID { get; set; }
        public Nullable<decimal> WardHospitalCharge { get; set; }
        public Nullable<int> StaffID { get; set; }
        public Nullable<int> MotherCompanyID { get; set; }
        public string Designation { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<decimal> BudgetAllowance { get; set; }
        public Nullable<decimal> BOIAllowance { get; set; }
        public Nullable<decimal> ManagementAllowance { get; set; }
        public Nullable<decimal> UniformAllowance { get; set; }
        public Nullable<decimal> TravelAllowance { get; set; }
        public Nullable<bool> ISresigned { get; set; }
        public Nullable<decimal> AttendanceIncentive { get; set; }
        public string RelatedPartyTitle { get; set; }
        public Nullable<decimal> PerformanceIncentive { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<System.DateTime> OpeningBalanceDate { get; set; }
        public Nullable<decimal> HostelFee { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
        public Nullable<bool> IsSetforPayroll { get; set; }
        public Nullable<int> PayeeTaxID { get; set; }
        public Nullable<bool> IsRosterAvailable { get; set; }
        public string Initials { get; set; }
        public string LastName { get; set; }
        public Nullable<int> RosterType { get; set; }
        public Nullable<int> RosterID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allowance> Allowances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollRecord> PayrollRecords { get; set; }
        public virtual RelatedPartyType RelatedPartyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedPartyDefaultSalaryModifier> RelatedPartyDefaultSalaryModifiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedPartySalary> RelatedPartySalaries { get; set; }
    }
}
