//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedPartySession
    {
        public int ID { get; set; }
        public Nullable<int> EPF { get; set; }
        public Nullable<int> PayMonth { get; set; }
        public Nullable<int> PayYear { get; set; }
        public Nullable<System.DateTime> CalendarDay { get; set; }
        public Nullable<int> DayTypeID { get; set; }
        public Nullable<System.DateTime> CheckInDateTime { get; set; }
        public Nullable<System.DateTime> CheckOutDateTime { get; set; }
        public Nullable<System.DateTime> ActualInDateTime { get; set; }
        public Nullable<System.DateTime> ActualOutDateTime { get; set; }
        public Nullable<int> WorkedMinutes { get; set; }
        public Nullable<int> EarlyInMinutes { get; set; }
        public Nullable<int> LateInMinutes { get; set; }
        public Nullable<int> EarlyOutMinutes { get; set; }
        public Nullable<int> LateOutMinutes { get; set; }
        public Nullable<int> OTMinutes { get; set; }
        public Nullable<int> RelatedPartyID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> AdmissionTypeID { get; set; }
        public string AdmissionNumber { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> ReceivedNurse { get; set; }
        public Nullable<int> NurseInChargeAdditional { get; set; }
        public Nullable<int> NurseInCharge { get; set; }
        public Nullable<int> AssistanceNurse { get; set; }
        public Nullable<int> RelatedPartyTyeID { get; set; }
        public Nullable<bool> IsHomeVisit { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsNurseInChargeAdditionalSatisfactory { get; set; }
        public Nullable<bool> IsNurseInChargeSatisfactory { get; set; }
        public Nullable<bool> IsAssistanceNurseSatisfactory { get; set; }
        public Nullable<bool> IsReceivedNurseSatisfactory { get; set; }
        public Nullable<int> Consultant { get; set; }
        public Nullable<int> NumberOfNoPayLeaveHours { get; set; }
        public Nullable<System.DateTime> NoPayleaveDate { get; set; }
        public Nullable<bool> IsOTPaid { get; set; }
        public Nullable<int> HomeVisitNurse { get; set; }
        public Nullable<decimal> LoginBalance { get; set; }
        public Nullable<decimal> LogoutBalance { get; set; }
        public string RelatedPartySessionNo { get; set; }
        public Nullable<int> UserSessionDivisionMasterID { get; set; }
        public Nullable<System.DateTime> AppointmentDateTime { get; set; }
        public Nullable<byte> SessionStatus { get; set; }
        public string MainConsultant { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> BedID { get; set; }
        public Nullable<decimal> BillTotal { get; set; }
        public Nullable<int> InsuranceCompanyID { get; set; }
        public Nullable<int> InsuranceCompanyBranchID { get; set; }
        public string OldAdmissionNumber { get; set; }
        public Nullable<int> AdmissionCategoryID { get; set; }
        public Nullable<bool> IsWithMeal { get; set; }
        public Nullable<bool> IsAirConditioned { get; set; }
        public string VisitReason { get; set; }
        public string Symtoms { get; set; }
        public string Treatments { get; set; }
        public string Comments { get; set; }
        public Nullable<int> RelatedPartySessionTypeID { get; set; }
        public Nullable<decimal> DrawerBalance { get; set; }
        public Nullable<decimal> ExcessOrShortage { get; set; }
        public Nullable<decimal> ActualCashBalance { get; set; }
        public Nullable<decimal> TotalSales { get; set; }
        public Nullable<decimal> TotalCancel { get; set; }
        public Nullable<decimal> TotalReturns { get; set; }
        public Nullable<decimal> CashBalace { get; set; }
        public Nullable<decimal> ChannelSales { get; set; }
        public Nullable<decimal> ScanSales { get; set; }
        public Nullable<decimal> LabSales { get; set; }
        public Nullable<decimal> XraySales { get; set; }
        public Nullable<int> Drawer { get; set; }
        public Nullable<decimal> ProcedureSales { get; set; }
        public Nullable<int> NextSessionID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> RecomendedHours { get; set; }
        public Nullable<int> WorkedDivision { get; set; }
        public string AttendanceStatus { get; set; }
        public Nullable<bool> IsRecommended { get; set; }
        public Nullable<bool> InvoiceNo { get; set; }
        public Nullable<System.DateTime> OverInDateTime { get; set; }
        public Nullable<System.DateTime> OverOutDateTime { get; set; }
        public Nullable<decimal> RecomendedOTHours { get; set; }
        public Nullable<bool> IsSetBillNo { get; set; }
        public Nullable<bool> IsAdmissionIncentive { get; set; }
        public Nullable<decimal> FinalBillTotal { get; set; }
        public Nullable<decimal> RecomendedLateHours { get; set; }
        public Nullable<decimal> RecomendedLieuHours { get; set; }
        public string FriendshipBy { get; set; }
        public Nullable<decimal> RecomendedFriendshipHours { get; set; }
        public Nullable<decimal> RecomendedCoverdHours { get; set; }
        public Nullable<decimal> RecomendedExcessHours { get; set; }
        public string FriendshipTo { get; set; }
        public Nullable<System.DateTime> AdditionalInDateTime { get; set; }
        public Nullable<System.DateTime> AdditionalOutDateTime { get; set; }
        public Nullable<bool> IsOTApproved { get; set; }
        public string ReasonsOfOT { get; set; }
        public Nullable<decimal> TotalWorkedHours { get; set; }
        public Nullable<int> RecommendHoursBy { get; set; }
        public Nullable<int> RecommendOTHoursBy { get; set; }
        public Nullable<int> TimeSlotID { get; set; }
        public string AppointmentNo { get; set; }
        public Nullable<decimal> HCGSales { get; set; }
        public Nullable<decimal> ECGSales { get; set; }
        public Nullable<decimal> TheatreSales { get; set; }
        public Nullable<decimal> VoucherPayments { get; set; }
        public Nullable<decimal> OPDSales { get; set; }
        public Nullable<decimal> InvoiceSales { get; set; }
        public Nullable<decimal> RecomendedDoubleOTHrs { get; set; }
        public Nullable<int> IsPosted { get; set; }
        public Nullable<int> IsCancelPosted { get; set; }
        public Nullable<decimal> PapsmearSale { get; set; }
        public Nullable<decimal> NoPayValue { get; set; }
        public Nullable<decimal> LeaveAppliedValue { get; set; }
        public Nullable<int> LateMinutes { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> ActualWorkedDepartment { get; set; }
        public Nullable<int> ActualShiftID { get; set; }
        public Nullable<int> LeaveStatus { get; set; }
        public Nullable<int> AdditionalLeaveStatus { get; set; }
        public Nullable<int> ActualLeaveStatus { get; set; }
        public Nullable<int> ActualAdditionalLeaveStatus { get; set; }
        public Nullable<int> LeaveCategoryID { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
        public Nullable<bool> IsAttendanceRemoved { get; set; }
        public string WeekDay { get; set; }
        public Nullable<int> InLateCount { get; set; }
        public Nullable<int> OutLateCount { get; set; }
        public Nullable<int> InLateHalfDayDeductionCount { get; set; }
        public Nullable<int> OutLateHalfDayDeductionCount { get; set; }
        public Nullable<decimal> IsWorked { get; set; }
        public Nullable<int> AdditionalShiftID { get; set; }
        public Nullable<int> AdditionalActualShiftID { get; set; }
        public Nullable<System.DateTime> AdditionalCheckInDateTime { get; set; }
        public Nullable<System.DateTime> AdditionalCheckOutDateTime { get; set; }
        public Nullable<int> IsShift { get; set; }
        public Nullable<int> FinalLateCount { get; set; }
        public Nullable<System.DateTime> LeauLeaveDay { get; set; }
        public Nullable<decimal> LeauLeaveValue { get; set; }
        public Nullable<System.DateTime> AdditionalActualCheckInDateTime { get; set; }
        public Nullable<System.DateTime> AdditionalActualCheckOutDateTime { get; set; }
        public Nullable<int> IsAdditionalShift { get; set; }
        public Nullable<int> AdditionalShiftRelatedOTMinutes { get; set; }
        public Nullable<decimal> ActualOTHours { get; set; }
        public Nullable<decimal> ActualWorkedHours { get; set; }
    }
}
