//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedPartySalaryModifierMapping
    {
        public int ID { get; set; }
        public Nullable<int> RelatedPartySalaryID { get; set; }
        public Nullable<int> SalaryModifierID { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public string GroupingForSlip { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string ActualAmount { get; set; }
        public string SalaryModifierName { get; set; }
        public Nullable<int> SalaryModifierTypeID { get; set; }
        public Nullable<bool> IsNoPay { get; set; }
        public Nullable<bool> IsLateHours { get; set; }
        public Nullable<int> TaxTypeID { get; set; }
        public Nullable<int> OTTypeID { get; set; }
        public Nullable<bool> IsEditable { get; set; }
        public Nullable<bool> IsAllawance { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
        public Nullable<bool> IsLoan { get; set; }
    
        public virtual RelatedPartySalary RelatedPartySalary { get; set; }
        public virtual SalaryModifier SalaryModifier { get; set; }
    }
}
