//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedPartyLeaveAllocation
    {
        public int ID { get; set; }
        public Nullable<int> RelatedPartyID { get; set; }
        public Nullable<int> HRYear { get; set; }
        public Nullable<int> LeaveCategoryID { get; set; }
        public Nullable<decimal> StartingValue { get; set; }
        public Nullable<System.DateTime> StartingValueDate { get; set; }
    }
}
