//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedPartyOrderPayment
    {
        public int ID { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string CreditCardNumber { get; set; }
        public string MCashCode { get; set; }
        public Nullable<System.DateTime> PaymentDateTime { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> CreditCardTypeID { get; set; }
        public Nullable<System.DateTime> CreditCardExpiryDate { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public Nullable<bool> IsAccountsRecommended { get; set; }
        public string RecommendedComment { get; set; }
        public Nullable<int> RecommendedUserID { get; set; }
        public Nullable<int> AdmissionID { get; set; }
    
        public virtual CreditCardType CreditCardType { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
