//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedPartyLoan1
    {
        public int ID { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<System.DateTime> LoanStartDate { get; set; }
        public Nullable<System.DateTime> LoanEndDate { get; set; }
        public Nullable<decimal> InterestPercentage { get; set; }
    }
}
