//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedPartySalary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RelatedPartySalary()
        {
            this.RelatedPartySalaryModifierMappings = new HashSet<RelatedPartySalaryModifierMapping>();
        }
    
        public int ID { get; set; }
        public Nullable<int> RelatedPartyEPF { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<decimal> NoPayDays { get; set; }
        public Nullable<int> LateMinutes { get; set; }
        public Nullable<int> OTMinutes { get; set; }
        public Nullable<int> RelatedPartyID { get; set; }
        public Nullable<bool> IsPayoutGenerated { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<int> SalaryTypeID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> DoubleOTMinutes { get; set; }
        public Nullable<decimal> PayeeTaxRate { get; set; }
        public Nullable<decimal> WorkedDays { get; set; }
        public Nullable<decimal> ActualNoPayDays { get; set; }
        public Nullable<decimal> ActualLateHours { get; set; }
        public Nullable<decimal> ActualOTHours { get; set; }
        public Nullable<decimal> ActualDBLOTHours { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<bool> IsAttendanceVerified { get; set; }
        public Nullable<int> TotalShifts { get; set; }
        public Nullable<int> TotalInLate { get; set; }
        public Nullable<int> TotalOutLate { get; set; }
        public Nullable<int> FinalLateCount { get; set; }
        public Nullable<int> TotalAdditionalShifts { get; set; }
    
        public virtual RelatedParty RelatedParty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedPartySalaryModifierMapping> RelatedPartySalaryModifierMappings { get; set; }
    }
}
