//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedPartyLoan
    {
        public int ID { get; set; }
        public Nullable<int> RelatedPartyID { get; set; }
        public Nullable<decimal> LoanTotalAmount { get; set; }
        public Nullable<decimal> MonthlyAmount { get; set; }
        public Nullable<int> NoOfInstallments { get; set; }
        public Nullable<System.DateTime> LoanStartDate { get; set; }
        public Nullable<int> LoanCategoryID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> LoanEndDate { get; set; }
    }
}
