//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedPartyDefaultSalaryModifier
    {
        public int ID { get; set; }
        public Nullable<int> RelatedPartyID { get; set; }
        public Nullable<int> SalaryModifierID { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<bool> IsPayee { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
    
        public virtual RelatedParty RelatedParty { get; set; }
        public virtual SalaryModifier SalaryModifier { get; set; }
    }
}
