//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedPartySalaryBankAccountsMapping
    {
        public int ID { get; set; }
        public Nullable<int> RelatedPartyID { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public Nullable<int> RelatedPartySalaryID { get; set; }
        public Nullable<int> RelatedPartyBankAccountID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
