//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedPartyOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RelatedPartyOrder()
        {
            this.RelatedPartyOrderDetails = new HashSet<RelatedPartyOrderDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> RelatedPartyID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<byte> OrderStatus { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> ChargeDiscountID { get; set; }
        public string RelatedPartyIdentityCardNo { get; set; }
        public Nullable<int> InvolvedPerson { get; set; }
        public Nullable<int> DivisionMasterID { get; set; }
        public Nullable<bool> IsNightTest { get; set; }
        public Nullable<int> AssignedPerson { get; set; }
        public Nullable<int> AdmissionTypeID { get; set; }
        public Nullable<bool> IsHomeVisit { get; set; }
        public Nullable<decimal> HomeVisitHospitalCharge { get; set; }
        public Nullable<int> RefPurchaseOrderID { get; set; }
        public Nullable<int> RelatedPartySessionID { get; set; }
        public Nullable<int> OperationTheatreAssistanceNurse { get; set; }
        public Nullable<int> OperationTheatreRunningNurse { get; set; }
        public Nullable<int> OperationTheatreMinusNurse { get; set; }
        public Nullable<decimal> OperationTheatreAssistanceNurseIncentiveValue { get; set; }
        public Nullable<decimal> OperationTheatreRunningNurseIncentiveValue { get; set; }
        public Nullable<decimal> OperationTheatreMinusNurseIncentiveValue { get; set; }
        public Nullable<bool> IsOrderReturned { get; set; }
        public Nullable<int> RefSalesOrderID { get; set; }
        public Nullable<int> RefGRNID { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public string BHTNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Deviation { get; set; }
        public Nullable<decimal> OPDDiscount { get; set; }
        public Nullable<int> PatientVisitID { get; set; }
        public string AppointmentNo { get; set; }
        public Nullable<int> ConsultantID { get; set; }
        public Nullable<int> RequestDivisionMasterID { get; set; }
        public Nullable<int> DistributorID { get; set; }
        public string InvoiceNo { get; set; }
        public string ConsultantName { get; set; }
        public Nullable<bool> isSafeDeleted { get; set; }
        public Nullable<int> TimeSlotID { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> OutSiderID { get; set; }
        public Nullable<int> Drawer { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<int> ConfirmedBy { get; set; }
        public Nullable<bool> isVerified { get; set; }
        public Nullable<bool> isPaid { get; set; }
        public Nullable<int> PaidBy { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<System.DateTime> AppointmentDateTime { get; set; }
        public string Times { get; set; }
        public Nullable<int> PaymentCategoryID { get; set; }
        public Nullable<int> NoOfprint { get; set; }
        public Nullable<int> IsPosted { get; set; }
        public Nullable<int> IsCancelPosted { get; set; }
        public Nullable<int> AccountingInvoiceID { get; set; }
        public string CancelReturnBy { get; set; }
        public Nullable<System.DateTime> CancelReturnDateTime { get; set; }
        public Nullable<System.DateTime> ReportGivenDate { get; set; }
        public Nullable<int> IsUrgent { get; set; }
        public Nullable<decimal> CashPaid { get; set; }
        public Nullable<int> SelectedDivisionMasterID { get; set; }
        public Nullable<int> PaymentSubCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedPartyOrderDetail> RelatedPartyOrderDetails { get; set; }
    }
}
