//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedPartyOrderDetail
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public Nullable<int> DivisionChargeID { get; set; }
        public string DivisionChargeName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> ChargeTypeID { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> ReorderLevel { get; set; }
        public Nullable<int> ChargeMasterPriceID { get; set; }
        public Nullable<bool> IsNurseCharge { get; set; }
        public Nullable<decimal> BonusQty { get; set; }
        public Nullable<decimal> DocFee { get; set; }
        public Nullable<decimal> HosFee { get; set; }
        public Nullable<decimal> WardDocFee { get; set; }
        public Nullable<int> BatchPopupID { get; set; }
        public Nullable<bool> IsNightTest { get; set; }
        public Nullable<int> involvedperson { get; set; }
        public Nullable<decimal> QtyPerPack { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<decimal> TechnicianCharge { get; set; }
        public Nullable<int> AttachmentID { get; set; }
        public Nullable<decimal> NurseFee { get; set; }
    
        public virtual RelatedPartyOrder RelatedPartyOrder { get; set; }
    }
}
