//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RosterStatu
    {
        public int ID { get; set; }
        public string DayStatusDescription { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> RosterRelated { get; set; }
        public Nullable<int> RosterTypeID { get; set; }
        public Nullable<decimal> NoOfMinutes { get; set; }
        public Nullable<bool> WithNextDay { get; set; }
    }
}
