//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryModifier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalaryModifier()
        {
            this.RelatedPartyDefaultSalaryModifiers = new HashSet<RelatedPartyDefaultSalaryModifier>();
            this.RelatedPartySalaryModifierMappings = new HashSet<RelatedPartySalaryModifierMapping>();
        }
    
        public int ID { get; set; }
        public string SalaryModifierName { get; set; }
        public Nullable<int> SalaryModifierTypeID { get; set; }
        public Nullable<bool> IsNoPay { get; set; }
        public Nullable<bool> IsLateHours { get; set; }
        public Nullable<int> TaxTypeID { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<int> OrderIndex { get; set; }
        public Nullable<int> OTTypeID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsBasicSalary { get; set; }
        public Nullable<bool> IsAllawance { get; set; }
        public Nullable<bool> IsEditable { get; set; }
        public Nullable<int> PreviousSalaryModifierID { get; set; }
        public Nullable<bool> IsRemoved { get; set; }
        public Nullable<bool> CommonValueForAll { get; set; }
        public Nullable<int> SalaryTypeID { get; set; }
        public Nullable<bool> IsLoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedPartyDefaultSalaryModifier> RelatedPartyDefaultSalaryModifiers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelatedPartySalaryModifierMapping> RelatedPartySalaryModifierMappings { get; set; }
    }
}
