//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryModifierDefaultValue
    {
        public int ID { get; set; }
        public Nullable<int> SalaryModifierID { get; set; }
        public Nullable<decimal> DefaultValue { get; set; }
        public Nullable<int> PayMonth { get; set; }
        public Nullable<int> PayYear { get; set; }
        public Nullable<int> SalaryTypeID { get; set; }
        public string SkipThisFor { get; set; }
    }
}
