//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public int ShiftID { get; set; }
        public string ShiftName { get; set; }
        public string ShiftCode { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public bool IsNightShift { get; set; }
        public bool IsOvertimeShift { get; set; }
        public decimal ShiftAllowance { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    }
}
