//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR_Application_CO_OP_HOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ward
    {
        public int WardID { get; set; }
        public string WardName { get; set; }
        public string WardCode { get; set; }
        public Nullable<int> LocationID { get; set; }
        public bool IsActive { get; set; }
    }
}
